version: '3'
services:
  neo4j:
    image: neo4j:5.18
    container_name: neo4j-tp
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - ./data:/data
