version: '3.8'
services:
  mongo-standalone:
    image: mongo:latest
    container_name: mongo-standalone
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: monpassword
    command: mongod --auth
